In [62]:
# No warnings
import warnings
warnings.filterwarnings('ignore') # Filter out warnings

# data analysis and wrangling
import pandas as pd
import numpy as np

# visualization
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

### Load Data

In [63]:
#Columns based on documentation
##Note: I added 3 dummy colunmns because the number of columns dont match with dataset

colnames=['ID', 'Birth Year', 'Gender Flag', 'Skillset1', 'Skillset1 Weight', 'Skillset2', 'Skillset2 Weight', 'City of profile','Country of profile','Education','Elite Institution', 'Start Date', 'StartFlag','End Date', 'EndFlag', 'CurrentEmployFlag','Length','Role','Dept','Company','Company_Norm','Ticker','Exchange','PublicFlag','Location','Industry','EducationFlag','DegreeType','EliteFlag','Dummy1','Dummy2','Dummy3'] 
len(colnames)

32

In [42]:
#Read the full romanians.csv
#Warning: May take some time
full_df = pd.read_csv('C:/AI4Good/romanians.csv',sep="\t")

In [44]:
full_df.head()

,0ec6dbef99b11f7ec15f9f6f18ada59f,1993,0,-1,0.1,-1.1,0.2,Unnamed: 7,Romania,0.3,False,2011-01-01,False.1,2011-01-01.1,False.2,False.3,0.4,engineer,Unnamed: 18,?,?.1,Unnamed: 21,ROMANIA,False.4,Unnamed: 24,54,False.5,Unnamed: 27,False.6,Unnamed: 29,Unnamed: 30,Unnamed: 31
0,0ec6dbef99b11f7ec15f9f6f18ada59f,1993,0,-1,0.000000,-1,0.000000,NaN,Romania,0,False,2011-01-01,False,2018-08-01,False,True,2769.0,NaN,NaN,MISSING,MISSING,MISSING,OTHER,False,Romania,MISSING,False,NaN,False,NaN,NaN,NaN
1,1c711330177d7e04b0b42b11a8e4650c,1989,1,Banking and Finance,0.996699,Accounting and Auditing,0.001583,NaN,Romania,0,False,2003-01-01,False,2007-01-01,False,False,1461.0,NaN,NaN,Academia de Studii Economice din BucureÈti,Academia de Studii Economice din BucureÈti,NaN,NaN,False,NaN,NaN,True,NaN,False,NaN,NaN,NaN
2,1c711330177d7e04b0b42b11a8e4650c,1989,1,Banking and Finance,0.996699,Accounting and Auditing,0.001583,NaN,Romania,0,False,2007-01-01,False,2009-01-01,False,False,731.0,NaN,NaN,Academia de Studii Economice din București,Academia de Studii Economice din București,NaN,NaN,False,NaN,NaN,True,NaN,False,NaN,NaN,NaN
3,1c711330177d7e04b0b42b11a8e4650c,1989,1,Banking and Finance,0.996699,Accounting and Auditing,0.001583,NaN,Romania,0,False,2007-04-01,True,2008-03-01,True,False,335.0,"Operator ghiseu,operator",NaN,Intesa San Paolo,Intesa San Paolo,NaN,NaN,False,NaN,NaN,False,NaN,False,NaN,NaN,NaN
4,1c711330177d7e04b0b42b11a8e4650c,1989,1,Banking and Finance,0.996699,Accounting and Auditing,0.001583,NaN,Romania,0,False,2008-03-01,True,2008-06-01,True,False,92.0,"Retail Officer,retail,officer",MARKETING,Intesa San Paolo bank,Intesa San Paolo bank,NaN,NaN,False,NaN,NaN,False,NaN,False,NaN,NaN,NaN

In [46]:
#no. of rows
full_df.shape[0]

5482351

In [47]:
#no. of columns
full_df.shape[1]

32

In [64]:
#Put the column names
full_df.columns=colnames

In [65]:
full_df.head()

,ID,Birth Year,Gender Flag,Skillset1,Skillset1 Weight,Skillset2,Skillset2 Weight,City of profile,Country of profile,Education,Elite Institution,Start Date,StartFlag,End Date,EndFlag,CurrentEmployFlag,Length,Role,Dept,Company,Company_Norm,Ticker,Exchange,PublicFlag,Location,Industry,EducationFlag,DegreeType,EliteFlag,Dummy1,Dummy2,Dummy3
0,0ec6dbef99b11f7ec15f9f6f18ada59f,1993,0,-1,0.000000,-1,0.000000,NaN,Romania,0,False,2011-01-01,False,2018-08-01,False,True,2769.0,NaN,NaN,MISSING,MISSING,MISSING,OTHER,False,Romania,MISSING,False,NaN,False,NaN,NaN,NaN
1,1c711330177d7e04b0b42b11a8e4650c,1989,1,Banking and Finance,0.996699,Accounting and Auditing,0.001583,NaN,Romania,0,False,2003-01-01,False,2007-01-01,False,False,1461.0,NaN,NaN,Academia de Studii Economice din BucureÈti,Academia de Studii Economice din BucureÈti,NaN,NaN,False,NaN,NaN,True,NaN,False,NaN,NaN,NaN
2,1c711330177d7e04b0b42b11a8e4650c,1989,1,Banking and Finance,0.996699,Accounting and Auditing,0.001583,NaN,Romania,0,False,2007-01-01,False,2009-01-01,False,False,731.0,NaN,NaN,Academia de Studii Economice din București,Academia de Studii Economice din București,NaN,NaN,False,NaN,NaN,True,NaN,False,NaN,NaN,NaN
3,1c711330177d7e04b0b42b11a8e4650c,1989,1,Banking and Finance,0.996699,Accounting and Auditing,0.001583,NaN,Romania,0,False,2007-04-01,True,2008-03-01,True,False,335.0,"Operator ghiseu,operator",NaN,Intesa San Paolo,Intesa San Paolo,NaN,NaN,False,NaN,NaN,False,NaN,False,NaN,NaN,NaN
4,1c711330177d7e04b0b42b11a8e4650c,1989,1,Banking and Finance,0.996699,Accounting and Auditing,0.001583,NaN,Romania,0,False,2008-03-01,True,2008-06-01,True,False,92.0,"Retail Officer,retail,officer",MARKETING,Intesa San Paolo bank,Intesa San Paolo bank,NaN,NaN,False,NaN,NaN,False,NaN,False,NaN,NaN,NaN

In [61]:
#Extracting just a subset to take a look
full_df.iloc[1:20, :]

,ID,Birth Year,Gender Flag,Skillset1,Skillset1 Weight,Skillset2,Skillset2 Weight,City of profile,Country of profile,Education,Elite Institution,Start Date,StartFlag,End Date,EndFlag,CurrentEmployFlag,Length,Role,Dept,Company,Company_Norm,Ticker,Exchange,PublicFlag,Location,Industry,EducationFlag,DegreeType,EliteFlag,Dummy,Dummy,Dummy
1,1c711330177d7e04b0b42b11a8e4650c,1989,1,Banking and Finance,0.996699,Accounting and Auditing,0.001583,NaN,Romania,0,False,2003-01-01,False,2007-01-01,False,False,1461.0,NaN,NaN,Academia de Studii Economice din BucureÈti,Academia de Studii Economice din BucureÈti,NaN,NaN,False,NaN,NaN,True,NaN,False,NaN,NaN,NaN
2,1c711330177d7e04b0b42b11a8e4650c,1989,1,Banking and Finance,0.996699,Accounting and Auditing,0.001583,NaN,Romania,0,False,2007-01-01,False,2009-01-01,False,False,731.0,NaN,NaN,Academia de Studii Economice din București,Academia de Studii Economice din București,NaN,NaN,False,NaN,NaN,True,NaN,False,NaN,NaN,NaN
3,1c711330177d7e04b0b42b11a8e4650c,1989,1,Banking and Finance,0.996699,Accounting and Auditing,0.001583,NaN,Romania,0,False,2007-04-01,True,2008-03-01,True,False,335.0,"Operator ghiseu,operator",NaN,Intesa San Paolo,Intesa San Paolo,NaN,NaN,False,NaN,NaN,False,NaN,False,NaN,NaN,NaN
4,1c711330177d7e04b0b42b11a8e4650c,1989,1,Banking and Finance,0.996699,Accounting and Auditing,0.001583,NaN,Romania,0,False,2008-03-01,True,2008-06-01,True,False,92.0,"Retail Officer,retail,officer",MARKETING,Intesa San Paolo bank,Intesa San Paolo bank,NaN,NaN,False,NaN,NaN,False,NaN,False,NaN,NaN,NaN
5,1c711330177d7e04b0b42b11a8e4650c,1989,1,Banking and Finance,0.996699,Accounting and Auditing,0.001583,NaN,Romania,0,False,2008-06-01,True,2010-02-01,True,False,610.0,"Corporate Officer,officer",BUSINESS,Intesa Sanpaolo,Intesa Sanpaolo,IITOF,PINX,True,NaN,522110,False,NaN,False,NaN,NaN,BBG000F4J290
6,1c711330177d7e04b0b42b11a8e4650c,1989,1,Banking and Finance,0.996699,Accounting and Auditing,0.001583,NaN,Romania,0,False,2010-03-01,True,2014-03-01,True,False,1461.0,"SME Underwriting Senior U. O,senior",NaN,Garanti Bank,garanti,NaN,ROMANIA,False,NaN,52,False,NaN,False,NaN,NaN,NaN
7,1c711330177d7e04b0b42b11a8e4650c,1989,1,Banking and Finance,0.996699,Accounting and Auditing,0.001583,NaN,Romania,0,False,2014-03-01,True,None,False,True,1628.0,"Commercial&SME Underwriting Coordinator,commer...",BUSINESS,Garanti Bank,garanti,NaN,ROMANIA,False,NaN,52,False,NaN,False,NaN,NaN,NaN
8,db24808a6a05b9908c7af8d21cd50c35,1995,1,"Energy, Oil, and Gas",0.999702,Industrial Management,0.000012,Aricestii Rahtivani,Romania,0,False,None,False,None,False,True,NaN,NaN,NaN,?,?,NaN,NaN,False,NaN,NaN,True,NaN,False,NaN,NaN,NaN
9,db24808a6a05b9908c7af8d21cd50c35,1995,1,"Energy, Oil, and Gas",0.999702,Industrial Management,0.000012,Aricestii Rahtivani,Romania,0,False,2013-07-01,True,2014-08-01,True,False,396.0,"Laboratory Technician,laboratory technician",NaN,AVA EASTERN EUROPE,AVA EASTERN EUROPE,NaN,NaN,False,NaN,NaN,False,NaN,False,NaN,NaN,NaN
10,db24808a6a05b9908c7af8d21cd50c35,1995,1,"Energy, Oil, and Gas",0.999702,Industrial Management,0.000012,Aricestii Rahtivani,Romania,0,False,2014-09-01,True,None,False,True,1444.0,Laboratory Tehnician,NaN,M-I SWACO,m-i swaco,NaN,ROMANIA,False,NaN,21,False,NaN,False,NaN,NaN,NaN
11,2340e3bdc451a860c3973d65359b0ed5,1977,2,Digital Marketing,0.586038,Sales Management,0.127705,NaN,Romania,0,False,1991-01-01,False,1996-01-01,False,False,1826.0,NaN,NaN,Academia de Studii Economice din București,Academia de Studii Economice din București,NaN,NaN,False,NaN,NaN,True,NaN,False,NaN,NaN,NaN
12,2340e3bdc451a860c3973d65359b0ed5,1977,2,Digital Marketing,0.586038,Sales Management,0.127705,NaN,Romania,0,False,1996-01-01,False,2015-07-01,True,False,7121.0,NaN,NaN,MISSING,MISSING,MISSING,OTHER,False,Romania,MISSING,False,NaN,False,NaN,NaN,NaN
13,2340e3bdc451a860c3973d65359b0ed5,1977,2,Digital Marketing,0.586038,Sales Management,0.127705,NaN,Romania,0,False,2015-08-01,True,None,False,True,1110.0,"Marketing Manager,marketing manager",MARKETING,BD Lemntech SRL,bd lemntech,NaN,ROMANIA,False,NaN,54,False,NaN,False,NaN,NaN,NaN
14,ab60dafc0eca62ac6f3a17747f1b0a94,2000,2,-1,0.000000,-1,0.000000,NaN,Ukraine,0,False,None,False,None,False,True,NaN,"Предприниматель,предприниматель",NaN,пп,пп,NaN,NaN,False,NaN,NaN,False,NaN,False,NaN,NaN,NaN
15,303b144bf8f02f160ae7c57c1fd50675,1979,2,Web Development,0.989416,Technical Product Management,0.009261,Lancaster,United States,0,False,1993-01-01,False,1997-01-01,False,False,1461.0,NaN,NaN,Elizabethtown College,Elizabethtown College,NaN,NaN,False,NaN,NaN,True,NaN,False,NaN,NaN,NaN
16,303b144bf8f02f160ae7c57c1fd50675,1979,2,Web Development,0.989416,Technical Product Management,0.009261,Lancaster,United States,0,False,1994-01-01,False,1994-01-01,False,False,0.0,NaN,NaN,Københavns Universitet,Københavns Universitet,NaN,NaN,False,NaN,NaN,True,NaN,False,NaN,NaN,NaN
17,303b144bf8f02f160ae7c57c1fd50675,1979,2,Web Development,0.989416,Technical Product Management,0.009261,Lancaster,United States,0,False,1997-11-01,True,2001-02-01,True,False,1188.0,"Programmer/Analyst,programmer/analyst",NaN,Turkey Hill Dairy,turkey hill,NaN,UNITED STATES,False,NaN,53,False,NaN,False,NaN,NaN,NaN
18,303b144bf8f02f160ae7c57c1fd50675,1979,2,Web Development,0.989416,Technical Product Management,0.009261,Lancaster,United States,0,False,2001-02-01,True,2009-06-01,True,False,3042.0,"Senior Information Systems Architect,senior,ar...",TECHNOLOGY,PSECU,psecu,NaN,UNITED STATES,False,NaN,52,False,NaN,False,NaN,NaN,NaN
19,303b144bf8f02f160ae7c57c1fd50675,1979,2,Web Development,0.989416,Technical Product Management,0.009261,Lancaster,United States,0,False,2009-07-01,True,None,False,True,3332.0,"Programmer/Analyst,programmer/analyst",NaN,Members 1st FCU,Members 1st FCU,NaN,NaN,False,NaN,NaN,False,NaN,False,NaN,NaN,NaN

In [71]:
full_df.set_index('ID')

,Birth Year,Gender Flag,Skillset1,Skillset1 Weight,Skillset2,Skillset2 Weight,City of profile,Country of profile,Education,Elite Institution,Start Date,StartFlag,End Date,EndFlag,CurrentEmployFlag,Length,Role,Dept,Company,Company_Norm,Ticker,Exchange,PublicFlag,Location,Industry,EducationFlag,DegreeType,EliteFlag,Dummy1,Dummy2,Dummy3
ID,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0ec6dbef99b11f7ec15f9f6f18ada59f,1993,0,-1,0.000000,-1,0.000000,NaN,Romania,0,False,2011-01-01,False,2018-08-01,False,True,2769.0,NaN,NaN,MISSING,MISSING,MISSING,OTHER,False,Romania,MISSING,False,NaN,False,NaN,NaN,NaN
1c711330177d7e04b0b42b11a8e4650c,1989,1,Banking and Finance,0.996699,Accounting and Auditing,0.001583,NaN,Romania,0,False,2003-01-01,False,2007-01-01,False,False,1461.0,NaN,NaN,Academia de Studii Economice din BucureÈti,Academia de Studii Economice din BucureÈti,NaN,NaN,False,NaN,NaN,True,NaN,False,NaN,NaN,NaN
1c711330177d7e04b0b42b11a8e4650c,1989,1,Banking and Finance,0.996699,Accounting and Auditing,0.001583,NaN,Romania,0,False,2007-01-01,False,2009-01-01,False,False,731.0,NaN,NaN,Academia de Studii Economice din București,Academia de Studii Economice din București,NaN,NaN,False,NaN,NaN,True,NaN,False,NaN,NaN,NaN
1c711330177d7e04b0b42b11a8e4650c,1989,1,Banking and Finance,0.996699,Accounting and Auditing,0.001583,NaN,Romania,0,False,2007-04-01,True,2008-03-01,True,False,335.0,"Operator ghiseu,operator",NaN,Intesa San Paolo,Intesa San Paolo,NaN,NaN,False,NaN,NaN,False,NaN,False,NaN,NaN,NaN
1c711330177d7e04b0b42b11a8e4650c,1989,1,Banking and Finance,0.996699,Accounting and Auditing,0.001583,NaN,Romania,0,False,2008-03-01,True,2008-06-01,True,False,92.0,"Retail Officer,retail,officer",MARKETING,Intesa San Paolo bank,Intesa San Paolo bank,NaN,NaN,False,NaN,NaN,False,NaN,False,NaN,NaN,NaN
1c711330177d7e04b0b42b11a8e4650c,1989,1,Banking and Finance,0.996699,Accounting and Auditing,0.001583,NaN,Romania,0,False,2008-06-01,True,2010-02-01,True,False,610.0,"Corporate Officer,officer",BUSINESS,Intesa Sanpaolo,Intesa Sanpaolo,IITOF,PINX,True,NaN,522110,False,NaN,False,NaN,NaN,BBG000F4J290
1c711330177d7e04b0b42b11a8e4650c,1989,1,Banking and Finance,0.996699,Accounting and Auditing,0.001583,NaN,Romania,0,False,2010-03-01,True,2014-03-01,True,False,1461.0,"SME Underwriting Senior U. O,senior",NaN,Garanti Bank,garanti,NaN,ROMANIA,False,NaN,52,False,NaN,False,NaN,NaN,NaN
1c711330177d7e04b0b42b11a8e4650c,1989,1,Banking and Finance,0.996699,Accounting and Auditing,0.001583,NaN,Romania,0,False,2014-03-01,True,None,False,True,1628.0,"Commercial&SME Underwriting Coordinator,commer...",BUSINESS,Garanti Bank,garanti,NaN,ROMANIA,False,NaN,52,False,NaN,False,NaN,NaN,NaN
db24808a6a05b9908c7af8d21cd50c35,1995,1,"Energy, Oil, and Gas",0.999702,Industrial Management,0.000012,Aricestii Rahtivani,Romania,0,False,None,False,None,False,True,NaN,NaN,NaN,?,?,NaN,NaN,False,NaN,NaN,True,NaN,False,NaN,NaN,NaN
db24808a6a05b9908c7af8d21cd50c35,1995,1,"Energy, Oil, and Gas",0.999702,Industrial Management,0.000012,Aricestii Rahtivani,Romania,0,False,2013-07-01,True,2014-08-01,True,False,396.0,"Laboratory Technician,laboratory technician",NaN,AVA EASTERN EUROPE,AVA EASTERN EUROPE,NaN,NaN,False,NaN,NaN,False,NaN,False,NaN,NaN,NaN
db24808a6a05b9908c7af8d21cd50c35,1995,1,"Energy, Oil, and Gas",0.999702,Industrial Management,0.000012,Aricestii Rahtivani,Romania,0,False,2014-09-01,True,None,False,True,1444.0,Laboratory Tehnician,NaN,M-I SWACO,m-i swaco,NaN,ROMANIA,False,NaN,21,False,NaN,False,NaN,NaN,NaN
2340e3bdc451a860c3973d65359b0ed5,1977,2,Digital Marketing,0.586038,Sales Management,0.127705,NaN,Romania,0,False,1991-01-01,False,1996-01-01,False,False,1826.0,NaN,NaN,Academia de Studii Economice din București,Academia de Studii Economice din București,NaN,NaN,False,NaN,NaN,True,NaN,False,NaN,NaN,NaN
2340e3bdc451a860c3973d65359b0ed5,1977,2,Digital Marketing,0.586038,Sales Management,0.127705,NaN,Romania,0,False,1996-01-01,False,2015-07-01,True,False,7121.0,NaN,NaN,MISSING,MISSING,MISSING,OTHER,False,Romania,MISSING,False,NaN,False,NaN,NaN,NaN
2340e3bdc451a860c3973d65359b0ed5,1977,2,Digital Marketing,0.586038,Sales Management,0.127705,NaN,Romania,0,False,2015-08-01,True,None,False,True,1110.0,"Marketing Manager,marketing manager",MARKETING,BD Lemntech SRL,bd lemntech,NaN,ROMANIA,False,NaN,54,False,NaN,False,NaN,NaN,NaN
ab60dafc0eca62ac6f3a17747f1b0a94,2000,2,-1,0.000000,-1,0.000000,NaN,Ukraine,0,False,None,False,None,False,True,NaN,"Предприниматель,предприниматель",NaN,пп,пп,NaN,NaN,False,NaN,NaN,False,NaN,False,NaN,NaN,NaN
303b144bf8f02f160ae7c57c1fd50675,1979,2,Web Development,0.989416,Technical Product Management,0.009261,Lancaster,United States,0,False,1993-01-01,False,1997-01-01,False,False,1461.0,NaN,NaN,Elizabethtown College,Elizabethtown College,NaN,NaN,False,NaN,NaN,True,NaN,False,NaN,NaN,NaN
303b144bf8f02f160ae7c57c1fd50675,1979,2,Web Development,0.989416,Technical Product Management,0.009261,Lancaster,United States,0,False,1994-01-01,False,1994-01-01,False,False,0.0,NaN,NaN,Københavns Universitet,Københavns Universitet,NaN,NaN,False,NaN,NaN,True,NaN,False,NaN,NaN,NaN
303b144bf8f02f160ae7c57c1fd50675,1979,2,Web Development,0.989416,Technical Product Management,0.009261,Lancaster,United States,0,False,1997-11-01,True,2001-02-01,True,False,1188.0,"Programmer/Analyst,programmer/analyst",NaN,Turkey Hill Dairy,turkey hill,NaN,UNITED STATES,False,NaN,53,False,NaN,False,NaN,NaN,NaN
303b144bf8f02f160ae7c57c1fd50675,1979,2,Web Development,0.989416,Technical Product Management,0.009261,Lancaster,United States,0,False,2001-02-01,True,2009-06-01,True,False,3042.0,"Senior Information Systems Architect,senior,ar...",TECHNOLOGY,PSECU,psecu,NaN,UNITED STATES,False,NaN,52,False,NaN,False,NaN,NaN,NaN
303b144bf8f02f160ae7c57c1fd50675,1979,2,Web Development,0.989416,Technical Product Management,0.009261,Lancaster,United States,0,False,2009-07-01,True,None,False,True,3332.0,"Programmer/Analyst,programmer/analyst",NaN,Members 1st FCU,Members 1st FCU,NaN,NaN,False,NaN,NaN,False,NaN,False,NaN,NaN,NaN
7bb878706a05ff7d8e10c6bc3ce46660,1982,2,-1,0.000000,-1,0.000000,Szczecin,Poland,0,False,2000-01-01,False,2011-01-01,False,False,4018.0,2end/Eng,NaN,Teekay Corporation,Teekay Corporation,TK,XNYS,True,NaN,483111,False,NaN,False,NaN,NaN,BBG000BLCJG8
7bb878706a05ff7d8e10c6bc3ce46660,1982,2,-1,0.000000,-1,0.000000,Szczecin,Poland,0,False,2011-01-01,False,2018-08-01,False,True,2769.0,NaN,NaN,MISSING,MISSING,MISSING,OTHER,False,Poland,MISSING,False,NaN,False,NaN,NaN,NaN
f4f393a13194eb3b71a9bb59affcefa6,1980,1,Sales Management,0.243114,Sales,0.118730,NaN,Romania,0,False,1998-01-01,False,2002-01-01,False,False,1461.0,NaN,NaN,Academia de Studii Economice,Academia de Studii Economice,NaN,NaN,False,NaN,NaN,True,NaN,False,NaN,NaN,NaN
f4f393a13194eb3b71a9bb59affcefa6,1980,1,Sales Management,0.243114,Sales,0.118730,NaN,Romania,0,False,1998-09-01,True,2002-04-01,True,False,1308.0,lucrator comercial-hostess,NaN,McDonald's Corporation,McDonald's Corporation,MCD,XNYS,True,NaN,722513,False,NaN,False,NaN,NaN,BBG000BNSZP1
f4f393a13194eb3b71a9bb59affcefa6,1980,1,Sales Management,0.243114,Sales,0.118730,NaN,Romania,0,False,2002-04-01,True,2003-05-01,True,False,395.0,NaN,NaN,TIME_OFF,TIME_OFF,TIME_OFF,OTHER,False,Romania,TIME_OFF,False,NaN,False,NaN,NaN,NaN
f4f393a13194eb3b71a9bb59affcefa6,1980,1,Sales Management,0.243114,Sales,0.118730,NaN,Romania,0,False,2003-06-01,True,2015-02-01,True,False,4263.0,sef serviciu economic,NaN,ABC TRADING CO SRL,ABC TRADING CO SRL,NaN,NaN,False,NaN,NaN,False,NaN,False,NaN,NaN,NaN
f4f393a13194eb3b71a9bb59affcefa6,1980,1,Sales Management,0.243114,Sales,0.118730,NaN,Romania,0,False,2015-03-01,True,None,False,True,1263.0,"Economist,economist",NaN,Strategic Research Corporation SA,strategic research corporation,NaN,ROMANIA,False,NaN,54,False,NaN,False,NaN,NaN,NaN
323f1693f747cf0dfae83d8847c61765,1999,2,-1,0.000000,-1,0.000000,NaN,Romania,0,False,None,False,None,False,True,NaN,"Owner,owner",OVERSIGHT,romstiv,romstiv,NaN,NaN,False,NaN,NaN,False,NaN,False,NaN,NaN,NaN
884e2af323c92162bdba9f7a630dabad,1999,0,-1,0.000000,-1,0.000000,NaN,Romania,0,False,None,False,None,False,True,NaN,"Operator,operator",NaN,Continental,Continental,UN,XNYS,True,NaN,54,False,NaN,False,NaN,NaN,BBG000CX7XX7
018f66f0130b81c9c2ceaeb735db4967,1985,1,Industrial Management,0.573454,Administration,0.188840,NaN,Romania,0,False,1999-01-01,False,2004-01-01,False,False,1826.0,NaN,NaN,?,?,NaN,NaN,False,NaN,NaN,True,NaN,False,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ddf68787d4c10a4f5cee91d3c9fb3326,1974,2,Pharmaceutical,0.448979,Software Engineering,0.221872,NaN,United Kingdom,0,False,2008-06-01,True,2009-01-01,True,False,214.0,"Medical Information Training Manager,training ...",HR,Janssen-Cilag,Janssen-Cilag,NaN,NaN,False,NaN,NaN,False,NaN,False,NaN,NaN,NaN
ddf68787d4c10a4f5cee91d3c9fb3326,1974,2,Pharmaceutical,0.448979,Software Engineering,0.221872,NaN,United Kingdom,0,False,2009-09-01,True,2010-03-01,True,False,181.0,"Validation Manager,manager",NaN,PV Solutions,pv,NaN,UNITED KINGDOM,False,NaN,54,False,NaN,False,NaN,NaN,NaN
ddf68787d4c10a4f5cee91d3c9fb3326,1974,2,Pharmaceutical,0.448979,Software Engineering,0.221872,NaN,United Kingdom,0,False,2010-03-01,True,2010-03-01,True,False,0.0,"MHRA / Validation Compliance Assessor,assessor",OVERSIGHT,Custom Healthcare Group,Custom Healthcare Group,NaN,NaN,False,NaN,NaN,False,NaN,False,NaN,NaN,NaN
ddf68787d4c10a4f5cee91d3c9fb3326,1974,2,Pharmaceutical,0.448979,Software Engineering,0.221872,NaN,United Kingdom,0,False,2010-03-01,True,2010-03-01,True,False,0.0,"Validation Compliance Assessor,assessor",OVERSIGHT,Oxford Biotherapeutics,Oxford Biotherapeutics,NaN,NaN,False,NaN,NaN,False,NaN,False,NaN,NaN,NaN
ddf68787d4c10a4f5cee91d3c9fb3326,1974,2,Pharmaceutical,0.448979,Software Engineering,0.221872,NaN,United Kingdom,0,False,2010-04-01,True,2010-04-01,True,False,0.0,"MHRA / Validation Compliance Assessor,assessor",OVERSIGHT,Brunel Healthcare,Brunel Healthcare,NaN,NaN,False,NaN,NaN,False,NaN,False,NaN,NaN,NaN
ddf68787d4c10a4f5cee91d3c9fb3326,1974,2,Pharmaceutical,0.448979,Software Engineering,0.221872,NaN,United Kingdom,0,False,2010-05-01,True,2010-11-01,True,False,184.0,Chairman of Global Regulatory Roadmap Working ...,NaN,BARQA,BARQA,NaN,NaN,False,NaN,NaN,False,NaN,False,NaN,NaN,NaN
ddf68787d4c10a4f5cee91d3c9fb3326,1974,2,Pharmaceutical,0.448979,Software Engineering,0.221872,NaN,United Kingdom,0,False,2010-07-01,True,2010-07-01,True,False,0.0,MHRA / Validation Compliance Assessor Patholog...,OVERSIGHT,Worthing Hospital,worthing,NaN,UNITED KINGDOM,False,NaN,62,False,NaN,False,NaN,NaN,NaN
ddf68787d4c10a4f5cee91d3c9fb3326,1974,2,Pharmaceutical,0.448979,Software Engineering,0.221872,NaN,United Kingdom,0,False,2010-08-01,True,2010-08-01,True,False,0.0,"ISO27001 Compliance Assessor,assessor",OVERSIGHT,Camden and Islington NHS Foundation Trust,camden and islington nhs,NaN,UNITED KINGDOM,False,NaN,62,False,NaN,False,NaN,NaN,NaN
ddf68787d4c10a4f5cee91d3c9fb3326,1974,2,Pharmaceutical,0.448979,Software Engineering,0.221872,NaN,United Kingdom,0,False,2010-11-01,True,2011-07-01,True,False,242.0,"Validation Consultant,consultant",NaN,Baxter Healthcare,Baxter Healthcare,BAX,XNYS,True,NaN,325414,False,NaN,False,NaN,NaN,BBG000BCVJ77
ddf68787d4c10a4f5cee91d3c9fb3326,1974,2,Pharmaceutical,0.448979,Software Engineering,0.221872,NaN,United Kingdom,0,False,2011-07-01,True,2015-04-01,True,False,1370.0,Validation Manager for LIMS Blood Transfusion ...,TECHNOLOGY,NHS Wales Informatics Services,NHS Wales Informatics Services,NaN,NaN,False,NaN,NaN,False,NaN,False,NaN,NaN,NaN
ddf68787d4c10a4f5cee91d3c9fb3326,1974,2,Pharmaceutical,0.448979,Software Engineering,0.221872,NaN,United Kingdom,0,False,2012-06-01,True,2012-08-01,True,False,61.0,"Infrastructure Qualification Consultant,consul...",NaN,Welsh Blood Service,Welsh Blood Service,NaN,NaN,False,NaN,NaN,False,NaN,False,NaN,NaN,NaN
ddf68787d4c10a4f5cee91d3c9fb3326,1974,2,Pharmaceutical,0.448979,Software Engineering,0.221872,NaN,United Kingdom,0,False,2014-01-01,True,2014-06-01,True,False,151.0,"Test Manager - Disclosure Management System,te...",NaN,Lycamobile,Lycamobile,NaN,NaN,False,NaN,NaN,False,NaN,False,NaN,NaN,NaN
ddf68787d4c10a4f5cee91d3c9fb3326,1974,2,Pharmaceutical,0.448979,Software Engineering,0.221872,NaN,United Kingdom,0,False,2015-04-01,True,2017-04-01,True,False,731.0,"Application and Integration Lead,lead",TECHNOLOGY,North Devon District Hospital,north devon district,NaN,UNITED KINGDOM,False,NaN,62,False,NaN,False,NaN,NaN,NaN
ddf68787d4c10a4f5cee91d3c9fb3326,1974,2,Pharmaceutical,0.448979,Software Engineering,0.221872,NaN,United Kingdom,0,False,2015-08-01,True,2017-04-01,True,False,609.0,"Project Quality Coach,project,quality,coach",NaN,North Devon District Hospital,north devon district,NaN,UNITED KINGDOM,False,NaN,62,False,NaN,False,NaN,NaN,NaN
ddf68787d4c10a4f5cee91d3c9fb3326,1974,2,Pharmaceutical,0.448979,Software Engineering,0.221872,NaN,United Kingdom,0,False,2016-08-01,True,2017-04-01,True,False,243.0,"Data Migration Lead,data,lead",NaN,North Devon District Hospital,north devon district,NaN,UNITED KINGDOM,False,NaN,62,False,NaN,False,NaN,NaN,NaN
ddf68787d4c10a4f5cee91d3c9fb3326,1974,2,Pharmaceutical,0.448979,Software Engineering,0.221872,NaN,United Kingdom,0,False,2017-04-01,True,2018-02-01,True,False,306.0,"Pharmacy Data Migration Lead,pharmacy,data,lead",NaN,North Devon District Hospital,north devon district,NaN,UNITED KINGDOM,False,NaN,62,False,NaN,False,NaN,NaN,NaN
ddf68787d4c10a4f5cee91d3c9fb3326,1974,2,Pharmaceutical,0.448979,Software Engineering,0.221872,NaN,United Kingdom,0,False,2018-02-01,True,None,False,True,196.0,IT Business Analyst and Compliance Specialist ...,"TECHNOLOGY,OVERSIGHT",British American Tobacco,British American Tobacco,BTI,XNYS,True,NaN,312230,False,NaN,False,NaN,NaN,BBG000MG1H82
6836fb3431715c6c77f569c36b531497,1999,0,-1,0.000000,-1,0.000000,NaN,Romania,0,False,None,False,None,False,True,NaN,jurist,NaN,?,?,NaN,ROMANIA,False,NaN,54,False,NaN,False,NaN,NaN,NaN
6f1775cda1d44160dbd37a96b1645c24,1995,0,-1,0.000000,-1,0.000000,NaN,Romania,0,False,None,False,None,False,True,NaN,"REFERENT,referent",NaN,SMITH&SMITH,smith&smith,NaN,ROMANIA,False,NaN,52,False,NaN,False,NaN,NaN,NaN
6f1775cda1d44160dbd37a96b1645c24,1995,0,-1,0.000000,-1,0.000000,NaN,Romania,0,False,2011-01-01,False,2014-01-01,False,False,1096.0,NaN,NaN,"Universitatea ""Titu Maiorescu""","Universitatea ""Titu Maiorescu""",NaN,NaN,False,NaN,NaN,True,NaN,False,NaN,NaN,NaN
6f1775cda1d44160dbd37a96b1645c24,1995,0,-1,0.000000,-1,0.000000,NaN,Romania,0,False,2013-05-01,True,2013-08-01,True,False,92.0,"Lucrator Comercial,comercial",NaN,Sc TabacInvest,Sc TabacInvest,NaN,NaN,False,NaN,NaN,False,NaN,False,NaN,NaN,NaN
6f1775cda1d44160dbd37a96b1645c24,1995,0,-1,0.000000,-1,0.000000,NaN,Romania,0,False,2013-09-01,True,2014-06-01,True,False,273.0,"Hostess,hostess",NaN,Wave Division,wave,NaN,ROMANIA,False,NaN,54,False,NaN,False,NaN,NaN,NaN
a22ab89b9681704f287b5bfa5c42c963,1999,2,-1,0.000000,-1,0.000000,NaN,Romania,0,False,None,False,None,False,True,NaN,telecomunicatii,NaN,home,home,UNEMPLOYED,ROMANIA,False,NaN,NaN,False,NaN,False,NaN,NaN,NaN
e38140ff2e1170b3c1bc559690c620e8,1999,2,-1,0.000000,-1,0.000000,NaN,Romania,0,False,None,False,None,False,True,NaN,Masinist,NaN,SC WimBosman SRL,SC WimBosman SRL,NaN,NaN,False,NaN,NaN,False,NaN,False,NaN,NaN,NaN
33ec39cea0a261de75d25fb19a047639,2000,2,-1,0.000000,-1,0.000000,Kutahya,Turkey,0,False,2005-01-01,False,2011-01-01,False,False,2191.0,Tanıtım Sorumlusu,NaN,BIOFARMA Pharmaceutical,biofarma,NaN,TURKEY,False,NaN,325412,False,NaN,False,NaN,NaN,NaN
33ec39cea0a261de75d25fb19a047639,2000,2,-1,0.000000,-1,0.000000,Kutahya,Turkey,0,False,2011-09-01,True,2015-01-01,True,False,1218.0,"Uzman Tanıtım Sorumlusu,uzman",NaN,GSK,GSK,GSK,XLON,True,NaN,325412,False,NaN,False,NaN,NaN,BBG000CT5GJ1
33ec39cea0a261de75d25fb19a047639,2000,2,-1,0.000000,-1,0.000000,Kutahya,Turkey,0,False,2015-07-01,True,None,False,True,1142.0,tanitim uzmani,NaN,Abdi Ibrahim Pharmaceuticals,abdi ibrahim,NaN,TURKEY,False,NaN,325412,False,NaN,False,NaN,NaN,NaN
33ec39cea0a261de75d25fb19a047639,2000,2,-1,0.000000,-1,0.000000,Kutahya,Turkey,0,False,2017-11-01,True,None,False,True,288.0,Tanıtım Uzmanı,NaN,Deva Holding A.Ş.,Deva Holding A.Ş.,NaN,NaN,False,NaN,NaN,False,NaN,False,NaN,NaN,NaN
5bbc740ba45ba718b8534850660edea6,1999,0,-1,0.000000,-1,0.000000,NaN,Romania,0,False,None,False,None,False,True,NaN,functionar public,NaN,primarie,primarie,NaN,NaN,False,NaN,NaN,False,NaN,False,NaN,NaN,NaN
84d3385c902ab0b02bb8c4f085f5f524,1999,0,-1,0.000000,-1,0.000000,NaN,Romania,0,False,None,False,None,False,True,NaN,quality expert on medicinal products,BUSINESS,National Medicines Agency (Romania),national medicines agency (romania),NaN,ROMANIA,False,NaN,713940,False,NaN,False,NaN,NaN,NaN

In [69]:
full_df[full_df['Dummy1'].notnull()][0:5]

,ID,Birth Year,Gender Flag,Skillset1,Skillset1 Weight,Skillset2,Skillset2 Weight,City of profile,Country of profile,Education,Elite Institution,Start Date,StartFlag,End Date,EndFlag,CurrentEmployFlag,Length,Role,Dept,Company,Company_Norm,Ticker,Exchange,PublicFlag,Location,Industry,EducationFlag,DegreeType,EliteFlag,Dummy1,Dummy2,Dummy3
17834,b366a80b1aa9f6c75a564ff3415def8d,1990,0,Web Development,0.768134,Technical Product Management,0.082479,NaN,Ireland,4,False,2010-01-01,False,2014-01-01,False,False,1461.0,"""Bachelor’s Degree, Computer Science"",Bachelor...",NaN,Facultatea de Inginerie in Limbi Straine - Uni...,Facultatea de Inginerie in Limbi Straine - Uni...,UNIVERSITY,IRELAND,False,NaN,NaN,True,4.0,False,computer science,Engineering,NaN
19847,4f303919ccda37e0329f980e41721dce,1981,1,-1,0.000000,-1,0.000000,NaN,Romania,5,False,2008-01-01,False,2010-01-01,False,False,731.0,"""Master's degree, Management and Business Comm...",NaN,S.N.S.P.A- Faculty of Communication and Public...,S.N.S.P.A- Faculty of Communication and Public...,UNIVERSITY,ROMANIA,False,NaN,NaN,True,5.0,False,management,Social Sciences,NaN
29765,b73393e8e27932c91e7266ff47e6ffcc,1977,2,-1,0.000000,-1,0.000000,Houston,United States,4,False,1995-01-01,False,2000-01-01,False,False,1826.0,"""Computer Science, Computer Science"",Computer ...",NaN,Southern University and Agricultural and Mecha...,Southern University and Agricultural and Mecha...,UNIVERSITY,UNITED STATES,False,NaN,NaN,True,4.0,False,computer science,Engineering,NaN
30459,fb78f4860ad580863bb5ee287b54b385,1983,1,Recruiting,0.287325,Human Resources (Senior),0.186252,NaN,United Kingdom,5,False,2008-01-01,False,2011-01-01,False,False,1096.0,"""BA (Hons), Sociology"",Hons,Sociology",NaN,University of Craiova,University of Craiova,UNIVERSITY,UNITED KINGDOM,False,NaN,NaN,True,4.0,False,sociology,Social Sciences,NaN
30462,fb78f4860ad580863bb5ee287b54b385,1983,1,Recruiting,0.287325,Human Resources (Senior),0.186252,NaN,United Kingdom,5,False,2012-01-01,False,2013-01-01,False,False,366.0,"""MA, Human Resources and Employment Management...",NaN,London Metropolitan University,London Metropolitan University,UNIVERSITY,UNITED KINGDOM,False,NaN,NaN,True,5.0,False,management,Social Sciences,NaN

In [70]:
full_df[full_df['Dummy3'].notnull()][0:5]

,ID,Birth Year,Gender Flag,Skillset1,Skillset1 Weight,Skillset2,Skillset2 Weight,City of profile,Country of profile,Education,Elite Institution,Start Date,StartFlag,End Date,EndFlag,CurrentEmployFlag,Length,Role,Dept,Company,Company_Norm,Ticker,Exchange,PublicFlag,Location,Industry,EducationFlag,DegreeType,EliteFlag,Dummy1,Dummy2,Dummy3
5,1c711330177d7e04b0b42b11a8e4650c,1989,1,Banking and Finance,0.996699,Accounting and Auditing,0.001583,NaN,Romania,0,False,2008-06-01,True,2010-02-01,True,False,610.0,"Corporate Officer,officer",BUSINESS,Intesa Sanpaolo,Intesa Sanpaolo,IITOF,PINX,True,NaN,522110,False,NaN,False,NaN,NaN,BBG000F4J290
20,7bb878706a05ff7d8e10c6bc3ce46660,1982,2,-1,0.000000,-1,0.000000,Szczecin,Poland,0,False,2000-01-01,False,2011-01-01,False,False,4018.0,2end/Eng,NaN,Teekay Corporation,Teekay Corporation,TK,XNYS,True,NaN,483111,False,NaN,False,NaN,NaN,BBG000BLCJG8
23,f4f393a13194eb3b71a9bb59affcefa6,1980,1,Sales Management,0.243114,Sales,0.118730,NaN,Romania,0,False,1998-09-01,True,2002-04-01,True,False,1308.0,lucrator comercial-hostess,NaN,McDonald's Corporation,McDonald's Corporation,MCD,XNYS,True,NaN,722513,False,NaN,False,NaN,NaN,BBG000BNSZP1
28,884e2af323c92162bdba9f7a630dabad,1999,0,-1,0.000000,-1,0.000000,NaN,Romania,0,False,None,False,None,False,True,NaN,"Operator,operator",NaN,Continental,Continental,UN,XNYS,True,NaN,54,False,NaN,False,NaN,NaN,BBG000CX7XX7
35,33b519f48a5532c2978cc4f220490ccd,1975,1,Sales Management,0.404712,Administration,0.086171,NaN,Honduras,0,False,1997-01-01,True,1998-01-01,True,False,365.0,"Oficial de Credito,oficial",NaN,"Creditlan, Visa",Visa,V,XNYS,True,NaN,522320,False,NaN,False,NaN,NaN,BBG000PSKYX7

In [75]:
print(pd.unique(full_df['Dummy1']))

[nan 'computer science' 'management' 'sociology' 'economics'
 'political science,humanities' 'political science' 'history'
 'mathematics,computer science' 'law' 'music' 'management,economics'
 'philosophy' 'electrical engineering' 'psychology'
 'german,philosophy,french' 'french' 'economics,political science'
 'architecture' 'mathematics' 'management,computer science'
 'religious studies,music' 'religious studies' 'music,history'
 'medieval studies,music' 'renaissance studies' 'french,history'
 'religious studies,french' 'sociology,american studies'
 'anthropology,sociology,american studies' 'linguistics' 'physics'
 'law,french' 'surgery' 'german,french' 'economics,physics'
 'sociology,psychology' 'nursing' 'chemistry,physics'
 'mathematics,physics' 'philosophy,architecture' 'philosophy,physics'
 'physics,history' 'humanities' 'classics' 'philosophy,classics'
 'pharmacology' 'philosophy,history' 'management,philosophy,history'
 'philosophy,economics' 'public health,management'
 'sociology,psychology,law' 'sociology,economics' 'comparative literature'
 'management,law' 'public health' 'biostatistics' 'genetics'
 'anthropology,sociology' 'economics,computer science'
 'mathematics,philosophy,physics' 'anthropology' 'sociology,philosophy'
 'classics,history' 'anthropology,sociology,psychology'
 'health care management,management' 'economics,french'
 'economics,history' 'chemistry' 'chemistry,philosophy'
 'religious studies,philosophy' 'german'
 'economics,political science,history'
 'architecture,history of art,history'
 'management,political science,economics'
 'mathematics,computer science,french' 'law,american studies'
 'philosophy,law' 'law,history' 'german,physics,history'
 'linguistics,philosophy' 'internal medicine' 'management,sociology'
 'classics,psychology' 'sociology,political science'
 'political science,history' 'anthropology,history'
 'mathematics,applied mathematics,computer science'
 'law,political science,history' 'economics,classics'
 'history of art,history' 'management,music' 'microbiology'
 'electrical engineering,computer science' 'philosophy,music'
 'management,computer science,philosophy,economics'
 'philosophy,religious studies' 'law,music' 'mathematics,philosophy'
 'english language & literature' 'mathematics,economics' 'astronomy'
 'philosophy,political science' 'mathematics,chemistry,physics,history'
 'physics,computer science' 'philosophy,chemistry' 'german,economics'
 'management,architecture' 'law,psychology' 'management,law,economics'
 'management,chemistry' 'philosophy,computer science'
 'german,mathematics,computer science'
 'mathematics,psychology,french,history' 'mathematics,chemistry,physics'
 'sociology,religious studies' 'management,psychology'
 'religious studies,psychology' 'classics,philosophy,history'
 'psychology,french,history' 'psychology,history' 'philosophy,psychology'
 'mathematics,management']